a=float(input("Digite o primeiro número "))
b=float(input("Digite o segundo número "))
c=float(input("digite o terceiro número "))
soma=round(a+b+c, 2)
sub= round(a-b-c,2)
mult= round(a*b*c, 2)
div= round(a/b/c, 2)
print("                                         ")
print("A soma dos termos a, b, e c, é igual a", soma)
print("                                         ")
print("A subtração dos termos a, b, e c, é igual a", sub)
print("                                         ")
print ("A multiplicação dos termos a, b, e c, é igual a", mult)
print("                                         ")
print("A soma dos termos a, b, e c, é igual a", div)
print("                                         ")