print("---------------------------")
print("       Questão 13")
print("---------------------------")
salariom=float(input("Digite o valor do salário minimo: "))
salario=float(input("digite o salário do funcionário(a): "))
salariof=round(salariom/salario, 1)
print(f"A quantidade de valores minimos é {salariof} ")