print("--------------------------")
print("        Questão 10")
print("--------------------------")
area1=float(input("Digite valor da base maior: "))
area2=float(input("Digite valor da base menor: "))
altura=float(input("Digite altura da área"))
trapezio=(area1+area2)*altura/2
print(f"O valor da base maior é {area1}")
print("    ")
print(f"O valor da base menor é {area2}")
print("   ")
print(f"O valor da altura é {altura}")
print("    ")
print(f"O valor do trapézio é {trapezio} ")